/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PageManagement;

import java.text.DecimalFormat;

/**
 *
 * @author deadoggy
 */
public class Fronter extends javax.swing.JFrame {

    /**
     * Creates new form Fronter
     */
    public Fronter() {
        initComponents();
        StatisticsTextField.setText("FIFO:\n" +
                                     "Running times: 0  Page fault rate: 0\n\n" +
                                    "LRU:\n" +
                                    "Running times: 0  Page fault rate: 0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MethodButtonGroup = new javax.swing.ButtonGroup();
        InsSizeLabel = new javax.swing.JLabel();
        InsSizeTextField = new javax.swing.JTextField();
        MemBlockSizeLabel = new javax.swing.JLabel();
        MemBlockSizeTextField = new javax.swing.JTextField();
        InsPerPageLabel = new javax.swing.JLabel();
        InsPerPageTextField = new javax.swing.JTextField();
        FIFORadioButton = new javax.swing.JRadioButton();
        LRURadioButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultTextField = new javax.swing.JTextArea();
        Run = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StatisticsTextField = new javax.swing.JTextArea();
        ResetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InsSizeLabel.setText("Ins Size");

        MemBlockSizeLabel.setText("Mem Block Size");

        InsPerPageLabel.setText("Ins Per Page");

        MethodButtonGroup.add(FIFORadioButton);
        FIFORadioButton.setSelected(true);
        FIFORadioButton.setText("FIFO");
        FIFORadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIFORadioButtonActionPerformed(evt);
            }
        });

        MethodButtonGroup.add(LRURadioButton);
        LRURadioButton.setText("LRU");
        LRURadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LRURadioButtonActionPerformed(evt);
            }
        });

        ResultTextField.setEditable(false);
        ResultTextField.setColumns(20);
        ResultTextField.setRows(5);
        jScrollPane1.setViewportView(ResultTextField);

        Run.setText("Run");
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });

        jLabel1.setText("Output:");

        jLabel2.setText("Statistics");

        StatisticsTextField.setEditable(false);
        StatisticsTextField.setColumns(20);
        StatisticsTextField.setRows(5);
        jScrollPane2.setViewportView(StatisticsTextField);

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FIFORadioButton)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LRURadioButton)
                                .addGap(101, 101, 101)
                                .addComponent(Run, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MemBlockSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(InsPerPageLabel)
                                .addGap(18, 18, 18)
                                .addComponent(InsPerPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(InsSizeLabel))
                                .addGap(18, 18, 18)
                                .addComponent(InsSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(MemBlockSizeLabel)
                                .addGap(291, 291, 291))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsSizeLabel)
                    .addComponent(InsSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MemBlockSizeLabel)
                    .addComponent(MemBlockSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsPerPageLabel)
                    .addComponent(InsPerPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FIFORadioButton)
                    .addComponent(LRURadioButton)
                    .addComponent(Run))
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(ResetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FIFORadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIFORadioButtonActionPerformed
        Method = 0;
    }//GEN-LAST:event_FIFORadioButtonActionPerformed

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        int InsSize = Integer.parseInt(InsSizeTextField.getText());
        int MemBlockSize = Integer.parseInt(MemBlockSizeTextField.getText());
        int InsPerPage = Integer.parseInt(InsPerPageTextField.getText());
        double res;
        Controller runController = null;
        if (0 == Method) {
            runController = new FIFOController(InsSize, MemBlockSize, InsPerPage);

        } else {
            runController = new LRUController(InsSize, MemBlockSize, InsPerPage);
        }
        res = runController.runInstructions();
        DecimalFormat DF = new DecimalFormat("#0.00");
        String MethodString;
        if(0 == Method)
        {
            MethodString = "FIFO";
            FIFORunTimes++;
            FIFORate = (FIFORate * (FIFORunTimes - 1) + res)/FIFORunTimes;
        }
        else
        {
            MethodString = "LRU";
            LRURunTimes++;
            LRURate = (LRURate * (LRURunTimes - 1) + res)/LRURunTimes;
        }
        ResultTextField.setText(ResultTextField.getText() + "InsSize: " + InsSizeTextField.getText()
                + "  Mem Block Size: " + MemBlockSizeTextField.getText()
                + "  InsPerPage: " + InsPerPageTextField.getText()
                + "  Method: " + MethodString
                + "  Page fault rate: "
                + DF.format(res) + "\n");
        DF = new DecimalFormat("#0.000000");
        StatisticsTextField.setText("FIFO:\n" +
                                    "Running times: "+FIFORunTimes+"  Page fault rate: "+DF.format(FIFORate)+"\n\n" +
                                    "LRU:\n" +
                                    "Running times: "+LRURunTimes+"  Page fault rate: "+DF.format(LRURate));
    }//GEN-LAST:event_RunActionPerformed

    private void LRURadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LRURadioButtonActionPerformed
        Method = 1;
    }//GEN-LAST:event_LRURadioButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        FIFORunTimes = 0;
        FIFORate = 0.0;
        LRURunTimes = 0;
        LRURate = 0.0;
        StatisticsTextField.setText("FIFO:\n" +
                                     "Running times: 0  Page fault rate: 0\n\n" +
                                    "LRU:\n" +
                                    "Running times: 0  Page fault rate: 0");
    }//GEN-LAST:event_ResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fronter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fronter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fronter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fronter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fronter().setVisible(true);
            }
        });
    }

    private int FIFORunTimes = 0;
    private int LRURunTimes = 0;
    private double FIFORate = 0.0;
    private double LRURate = 0.0;
    private int Method = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FIFORadioButton;
    private javax.swing.JLabel InsPerPageLabel;
    private javax.swing.JTextField InsPerPageTextField;
    private javax.swing.JLabel InsSizeLabel;
    private javax.swing.JTextField InsSizeTextField;
    private javax.swing.JRadioButton LRURadioButton;
    private javax.swing.JLabel MemBlockSizeLabel;
    private javax.swing.JTextField MemBlockSizeTextField;
    private javax.swing.ButtonGroup MethodButtonGroup;
    private javax.swing.JButton ResetButton;
    private javax.swing.JTextArea ResultTextField;
    private javax.swing.JButton Run;
    private javax.swing.JTextArea StatisticsTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
